### ISSUE TITLE
RNBO Parameters working in Max/Msp but Unity doesn't see them. 

### ISSUE THREAD

**Issue by JimPapanick** [Cycling74/rnbo.unity.audioplugin#45]
I have done various small plugins in Unity and I have successfully done pretty much the same thing I'm trying to do now various times. Suddenly today the parameters that ARE changing , do not show that anything is happening when I debug them through a script. I basically have copied and pasted past plugins and re-exported them and their newly exported versions are broken aswell. So I think that something is wrong with my Unity/Rnbo/Cmake (max/msp was also updated and i still have the same issue). 

I'm at my wits end. 
SO

During export through CMAKE on CMD, do you find any weird messages in this log?
Copy and pasted from CMD.

D:\>cd D:\Unity\RNBO\rnbo.unity.audioplugin-main\build

D:\Unity\RNBO\rnbo.unity.audioplugin-main\build>cmake .. -DPLUGIN_NAME="Fzero4"
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- building for WindowsStandalone64 with bit depth 64 for CPU AMD64
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: D:/Unity/RNBO/rnbo.unity.audioplugin-main/build

D:\Unity\RNBO\rnbo.unity.audioplugin-main\build>cmake --build .
MSBuild version 17.6.3+07e294721 for .NET Framework

  RNBOWrapper.cpp
  AudioPluginUtil.cpp
  rnbo_source.cpp
  RNBO.cpp
  Generating Code...
     Creating library D:/Unity/RNBO/rnbo.unity.audioplugin-main/build/Debug/Fzero4.lib and object D:/Unity/RNBO/rnbo.un
  ity.audioplugin-main/build/Debug/Fzero4.exp
  RNBOUnityPlugin.vcxproj -> D:\Unity\RNBO\rnbo.unity.audioplugin-main\build\Fzero4\Assets\Plugins\Windows\Fzero4.dll

D:\Unity\RNBO\rnbo.unity.audioplugin-main\build>

**Comment by JimPapanick** [comment]
A screenshot example of what I'm experiencing. 
1: I have input on my audio source, the input does have output (i can hear it)
2: The parameter in the patcher works just fine as you can see on the right
3: The parameter in Unity seems idle both in the inspector and through the script that I'm handling it

Please help!!
![image](https://github.com/user-attachments/assets/9a349652-0754-486f-bee8-c8c8dca7bd35)

**Comment by jinpavg** [comment]
Hi Jim, thank you for reaching out here and sharing this example. Yes, I think I can see what's up here. There are basically two issues -

1. It doesn't look like you've set an [instance index](https://github.com/Cycling74/rnbo.unity.audioplugin/blob/main/docs/GETTING_STARTED.md#loading-your-plugin-on-an-audio-mixer) for the RNBO plugin on the Mixer. Without this, you won't be able to address this _particular_ instance of your RNBO plugin from script. 

2. Unity's GUI for audio parameters includes slider that don't necessarily reflect the present value of the parameter in your RNBO plugin. Instead of calling `GetFloat()` on the audio mixer, I'd recommend you get the value of the parameter directly from your RNBO plugin, by calling `GetParamValue()`. You can see the documentation for that here: https://github.com/Cycling74/rnbo.unity.audioplugin/blob/main/docs/PARAMETERS.md#getting-a-parameter-value

So in your situation, it doesn't look like your script has a reference to this instance of the RNBO Plugin. It's possible that the plugin is functioning (after all, it is passing audio), but we don't know if it is because we are just asking the audio mixer what the value of the slider named `"FzeroHzAmount"` is, which is always 0. 

If you set up your script to address a particular instance of your device, as in the "GETTING STARTED" article above, and get the value of the parameter directly from that plugin, it should become clear whether your plugin is in fact changing the value of your parameter or not. 

Certainly let me know if I can help further!
