### ISSUE TITLE
This RNBO UnityPlugin does not work with WebGL builds.

### ISSUE THREAD

**Issue by tomo0407** [Cycling74/rnbo.unity.audioplugin#47]
Thanks to this repository, I was able to convert the RNBO patch into a UnityPlugin. Thank you.

On the other hand, when the created application was built in HTML5, no sound was produced and the following error appeared in the console.

`Output.framework.js.gz:10 Audio effect My Custom Plugin could not be found. Check that the project contains the correct native audio plugin libraries and that the importer settings are set up correctly.
_JS_Log_Dump	@	Output.framework.js.gz:10`

It seems that the plugin I created (My Custom Plugin) is not properly tied to the build.

Does this RNBO plugin for Unity support WebGL builds?

Do you know how to use RNBO's Unity plugin for web application builds?

**Comment by jinpavg** [comment]
Hi @tomo0407 , thank you for reaching out here and checking out this repo. 

No, this plugin will not function in a Unity WebGL build, this is because Unity uses a very different audio implementation for WebGL, you can read more about it here: https://docs.unity3d.com/2018.3/Documentation/Manual/webgl-audio.html

However, you can certainly use RNBO for audio in a Unity WebGL project. I'd recommend a strategy like this

- use RNBO's Web Export to get WASM audio code: https://rnbo.cycling74.com/learn/the-web-export-target
- create a .jslib plug-in: https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html
- write C# scripts that use that .jslib plug-in
- make your Unity WebGL build
- create an index.html file that pulls it all together

I actually have an example of this, with a tutorial, but I want to caution you that this tutorial is very old, and references an earlier version of Unity, and earlier version of RNBO, and many of the links will be broken: https://github.com/jinpavg/rnbo-unity-webgl/blob/main/unity-tutorial.md

However, there is a working example of what I've described in this repo there, you can find a simple `.jslib` plugin in `unity-scripts/Plugins/`
